name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      # Run compiler
      - name: Compile css
        run: dart run

      - name: Check for changes
        run: |
          if git diff --cached --exit-code --quiet; then
            echo "No changes to commit."
            exit 0
          else
            echo "Changes found. Committing..."
          fi

      - name: Commit changes
        if: success()
        run: |
              git config --local user.email "actions@github.com"
              git config --local user.name "GitHub Actions"
              git add .
              git commit -m "Compilação do css"

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main