name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          dart-sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Compile css
        run: dart run

      - name: Check for changes
        if: success()
        id: check_changes
        run: |
          if git diff --exit-code --quiet; then
            echo "No changes to commit."
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "Changes found. Committing..."
            echo "has_changes=true" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Commit changes
        if: success() && steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Compilação do css"

      - name: Push changes
        if: success() && steps.check_changes.outputs.has_changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
